// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLg5PM8urIBjZX9oMCl_KYUGWi64wy2Qs',
    appId: '1:148735114448:web:4b074d1687f023efc1f2d5',
    messagingSenderId: '148735114448',
    projectId: 'getwork-b4c9f',
    authDomain: 'getwork-b4c9f.firebaseapp.com',
    storageBucket: 'getwork-b4c9f.appspot.com',
    measurementId: 'G-Z58EWHGYB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWw1RU-pzol9xOT8mycWtiRsPWR3rDPmM',
    appId: '1:148735114448:android:cc4496959c4f13aec1f2d5',
    messagingSenderId: '148735114448',
    projectId: 'getwork-b4c9f',
    storageBucket: 'getwork-b4c9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDPgk72m7MwYIoWbiDOR3vJAxPZb578zQ',
    appId: '1:148735114448:ios:979138d565a4ec96c1f2d5',
    messagingSenderId: '148735114448',
    projectId: 'getwork-b4c9f',
    storageBucket: 'getwork-b4c9f.appspot.com',
    iosBundleId: 'com.example.getWork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDPgk72m7MwYIoWbiDOR3vJAxPZb578zQ',
    appId: '1:148735114448:ios:979138d565a4ec96c1f2d5',
    messagingSenderId: '148735114448',
    projectId: 'getwork-b4c9f',
    storageBucket: 'getwork-b4c9f.appspot.com',
    iosBundleId: 'com.example.getWork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLg5PM8urIBjZX9oMCl_KYUGWi64wy2Qs',
    appId: '1:148735114448:web:c580007e50555f3cc1f2d5',
    messagingSenderId: '148735114448',
    projectId: 'getwork-b4c9f',
    authDomain: 'getwork-b4c9f.firebaseapp.com',
    storageBucket: 'getwork-b4c9f.appspot.com',
    measurementId: 'G-S9RQNEYXWG',
  );
}
